export enum ProcessingState {
  IDLE = 'IDLE',
  CONFIGURING_CLEANING = 'CONFIGURING_CLEANING',
  CONFIGURING_HEADLINES = 'CONFIGURING_HEADLINES',
  CONFIGURING_FOOTNOTES = 'CONFIGURING_FOOTNOTES',
  CONFIGURING_CONTENT = 'CONFIGURING_CONTENT',
  EXTRACTING = 'EXTRACTING',
  OCR = 'OCR',
  CLEANING = 'CLEANING',
  STRUCTURING_HEADLINES = 'STRUCTURING_HEADLINES',
  STRUCTURING_FOOTNOTES = 'STRUCTURING_FOOTNOTES',
  STRUCTURING_CONTENT = 'STRUCTURING_CONTENT',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}

export enum DownloadFormat {
  CLEANED_TEXT = 'CLEANED_TEXT',
  HEADLINES_ONLY = 'HEADLINES_ONLY',
  FULLY_STRUCTURED = 'FULLY_STRUCTURED',
  MARKER_STAGE = 'MARKER_STAGE',
}

export enum ProcessingMode {
  FAST = 'FAST',
  QUALITY = 'QUALITY',
}
